name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build frontend
      run: |
        cd MERN-Stack-Ecommerce-App-master
        npm install
        CI=false npm run build

    - name: Copy build folder to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 13.234.4.41
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "MERN-Stack-Ecommerce-App-master/build/*"
        target: "/var/www/html"

    - name: Fix permissions and restart Nginx
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 13.234.4.41
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          sudo systemctl restart nginx
